
eureka:
  instance:
    instance-id: config1
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8000/eureka

  server:
    enable-self-preservation: true

defale:
  file-path: D:// root
  
  
a: bb
